<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
    <PackageReference Include="PDFsharp" Version="6.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Joonasw.ElectronicSigningDemo.WorkflowModels\Joonasw.ElectronicSigningDemo.WorkflowModels.csproj" />
  </ItemGroup>

</Project>
